[package]
name = "tonic-build"
version = "0.1.0"
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost-build = "0.5"
codegen = "0.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
